### ISSUE TITLE
Non-minified source code for *.css & script.js are missing

### ISSUE THREAD

**Issue by trongthanh** [paambaati/nodequiz#1]
I'm interested in implementing an open-source quiz maker based on this repo. However, I cannot find the non-minified source of the *.css and script.js from which I'd like to modify further. I guess you were using automation tooling to minify the css and js during authoring.

Can you please commit the full version of said files?

Thanks.

**Comment by paambaati** [comment]
Sadly, I've lost those. I was careless, considering this just a learning exercise, and never backed up anything. I'm sorry I couldn't help.

**Comment by trongthanh** [comment]
OK then. :(
